-d C:\Users\hgszh\Desktop\AD-DA\impl\gwsynthesis\AD-DA.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\hgszh\Desktop\AD-DA\src\AD-DA.cst
-cfg C:\Users\hgszh\Desktop\AD-DA\impl\pnr\device.cfg
-sdc C:\Users\hgszh\Desktop\AD-DA\src\AD-DA.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
